#!/usr/bin/env node
/* =============================================================================
   sync-glass.mjs — vendors @abheet19/glass's base tokens into the client bundle.

   glass (https://github.com/abheet19/glass) lives in a sibling repo, not this
   monorepo's workspace, and Weft's Fly.io Dockerfile builds from a context
   that is this repo only (COPY . . — no sibling directory reachable). A
   `file:../../glass` npm dependency would resolve on a dev machine that has
   both repos checked out side by side, but would break `npm ci` inside the
   Docker build, which is the one gate this script must never risk.

   So the real dependency is expressed as a committed, generated vendor copy
   instead of a live npm link: run this script (from a machine with glass
   checked out at ../glass, i.e. a sibling of this repo) whenever glass's
   tokens.css changes, and commit the result. It is byte-identical to glass's
   src/tokens.css at the time it was run — diff it against
   ../glass/src/tokens.css to confirm it is current.
   ============================================================================= */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const src = resolve(root, '..', 'glass', 'src', 'tokens.css');

if (!existsSync(src)) {
  console.error(`sync-glass: ${src} not found. Check out abheet19/glass as a sibling of this repo first.`);
  process.exit(1);
}

const destDir = resolve(root, 'packages/client/src/ui/vendor');
const dest = resolve(destDir, 'glass-base.css');
if (!existsSync(destDir)) mkdirSync(destDir, { recursive: true });

const banner = `/* AUTO-GENERATED by tools/sync-glass.mjs from https://github.com/abheet19/glass (src/tokens.css). Do not edit directly — edit glass and re-run the script. */\n`;
writeFileSync(dest, banner + readFileSync(src, 'utf8'), 'utf8');
console.log(`sync-glass: vendored ${src} -> ${dest}`);
